# .github/actions/install-dependencies-yarn/action.yml
name: 'Install Dependencies'
description: 'Installs dependencies using yarn'

runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
    - name: Cache yarn dependencies
      uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --immutable
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      shell: bash
