# .github/actions/setup-playwright/action.yml
name: 'Setup Playwright'
description: 'Installs Playwright browsers and system dependencies'

runs:
  using: 'composite'
  steps:
    - name: Cache Playwright Browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-
    - name: Install Playwright Dependencies (Browsers + System)
      run: npx playwright install --with-deps
      shell: bash
