# .github/workflows/reusable-snyk-scan.yml
name: Reusable Snyk Scan

on:
  workflow_call:
    secrets:
      # Ожидаем SNYK_TOKEN от родительского воркфлоу (ci.yml)
      SNYK_TOKEN:
        required: true

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies-npm

      - name: Install Snyk CLI
        run: npm install --location=global snyk

      - name: Authenticate Snyk
        run: snyk auth "$SNYK_TOKEN"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source Scan
        run: snyk test --all-projects --sarif-file-output=snyk-test.sarif --exclude=.nx,dist
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Run Snyk Code Scan
        run: snyk code test --sarif-file-output=snyk-code.sarif --exclude=.nx,dist
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk Open Source results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-test.sarif

      - name: Upload Snyk Code results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
